// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Import types for image API
import type {
  ProcessImageRequest,
  ProcessImageResponse,
  SelectFolderResponse,
  SaveFileRequest,
  SaveFileResponse,
} from "./helpers/ipc/image/image-channels";

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

declare interface Window {
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  imageAPI: {
    processImage: (
      request: ProcessImageRequest,
    ) => Promise<ProcessImageResponse>;
    selectFolder: () => Promise<SelectFolderResponse>;
    saveFile: (request: SaveFileRequest) => Promise<SaveFileResponse>;
    getDownloadsPath: () => Promise<string>;
  };
}

export {};
